### ISSUE TITLE
MacOS aborted installation with warning: MacOS was unable to verify that the App did not contain malware

### ISSUE THREAD

**Issue by Bin-Huang** [RenzHoly/Mongood#152]
![image](https://user-images.githubusercontent.com/20723142/103659359-47f05e80-4fa7-11eb-8f47-99eb190380b3.png)

Anything we can do for this?

**Comment by RenzHoly** [comment]
right click to open and trust

**Comment by RenzHoly** [comment]
https://support.apple.com/zh-hk/guide/mac-help/mh40616/mac
