### ISSUE TITLE
Pre-built Mac binary does not open

### ISSUE THREAD

**Issue by ericschmar** [renzholy/mongood#166]
I tried downloading the pre-built Mac binary and running, and no windows pop up, nothing. No errors. Just simply doesn't open.

I make sure to right-click open, and no prompt about un-verified developer. 

I'm on macOS Big Sur 11.6, MacBook Pro 16" with intel processor

**Comment by renzholy** [comment]
did you installed chrome?

**Comment by ericschmar** [comment]
> did you installed chrome?

That did the trick! I thought I had chrome installed, but didn't check. Thanks!
