### ISSUE TITLE
Connection editing

### ISSUE THREAD

**Issue by Ilya-666** [renzholy/mongood#168]
Hi,
Thanks for making this available. I downloaded the windowsx64 executable. The edit connection window didn't allow me to edit the connection details, didn;t seem to respond to keyboard or mouse input, so I haven't got beyond there. I will try downloading the linux version and then the source code to see if the connection is hard coded but thought I should alert you to this as it looks like it might be a useful tool but shame to have this as first hurdle.

**Comment by renzholy** [comment]
Hi,
I have no idea about the bug of windows version. Connection edit works fine on my macOS.
connection is not hard coded, It can be specified through both environment variable and connection edit GUI.
