### ISSUE TITLE
build error: Type '() => any' is not a constructor function type.

### ISSUE THREAD

**Issue by drgnchan** [renzholy/mongood#169]
when i run `yarn build`
console output a error message:
Type error: Type '() => any' is not a constructor function type.

  13 |  * @see https://github.com/microsoft/fluentui/wiki/Server-side-rendering-and-browserless-testing
  14 |  */
> 15 | export default class MyDocument extends Document<{
     |                                         ^
  16 |   styleTags: string
  17 |   serializedStylesheet: string
  18 | }> {

**Comment by renzholy** [comment]
Bug fixed! please pull and run `yarn install` then try again

**Comment by drgnchan** [comment]
> Bug fixed! please pull and run `yarn install` then try again

it helps.Thanks a lot!
