### ISSUE TITLE
在国内，是新手，各种依赖拉不了，蠢到哭，跪求在Release中加入编译好程序

### ISSUE THREAD

**Issue by CallMeBatMan** [RenzHoly/Mongood#67]

**Comment by genshen** [comment]
For go side, you can use go proxy by setting `GOPROXY`  environment variable.
e.g.
```bash
export GOPROXY=https://goproxy.io,direct
cd go && go mod download # then you can download Go dependencies via goproxy.io proxy.
make
```

For node/typescript side, you can use [Taobao NPM mirror](https://developer.aliyun.com/mirror/NPM) (for **npm** as package manager tool).

**Comment by RenzHoly** [comment]
https://github.com/RenzHoly/Mongood/releases

**Comment by CallMeBatMan** [comment]
> 对于go端，可以通过设置`GOPROXY` 环境变量来使用go proxy 。
> 例如
> 
> ```shell
> 导出GOPROXY = https：//goproxy.io，直接
> cd go && go mod download ＃然后您可以通过goproxy.io代理下载Go依赖项。
> 使
> ```
> 
> 对于节点/打字稿方面，您可以使用[淘宝NPM镜像](https://developer.aliyun.com/mirror/NPM)。
> 例如
> 
> ```shell
> ＃将npm用作软件包管理器
> npm config设置注册表https://registry.npm.taobao.org/
> ```
> 
> 或（如果您使用纱线作为卷装管理器）：
> 
> ```shell
> ＃使用yarn作为程序包管理器
> yarn配置集注册表https://registry.npm.taobao.org/
> ```
> 
> 如果是自己编译的话，通过设置代理或可以帮到您。
> 转到这边，可以设置`GOPROXY `环境变量来使用代理以拉取依赖包。
> 
> ```shell
> 导出GOPROXY = https：//goproxy.io，直接
> cd go && go mod下载＃通过代理goproxy.io来Go的拉取依赖包
> make
> ```
> 
> 对于node / typescript这块，可以使用[淘宝NPM更长](https://developer.aliyun.com/mirror/NPM)。
> 例如：
> 
> ```shell
> ＃使用npm包管理器
> npm配置集注册表https://registry.npm.taobao.org/
> ```
> 
> 或者：
> 
> ```shell
> ＃使用yarn包管理器
> 纱线配置设置注册表https://registry.npm.taobao.org/
> ```



> For go side, you can use go proxy by setting `GOPROXY` environment variable.
> e.g.
> 
> ```shell
> export GOPROXY=https://goproxy.io,direct
> cd go && go mod download # then you can download Go dependencies via goproxy.io proxy.
> make
> ```
> 
> For node/typescript side, you can use [Taobao NPM mirror](https://developer.aliyun.com/mirror/NPM).
> e.g.
> 
> ```shell
> # use npm as package manager
> npm config set registry https://registry.npm.taobao.org/
> ```
> 
> or (if you are using yarn as package manager):
> 
> ```shell
> # use yarn as package manager
> yarn config set registry https://registry.npm.taobao.org/
> ```
> 
> 如果是自己编译的话，通过设置代理或者可以帮到您。
> Go 这边，可以设置`GOPROXY ` 环境变量来使用代理以拉取依赖包。例如：
> 
> ```shell
> export GOPROXY=https://goproxy.io,direct
> cd go && go mod download # 通过代理 goproxy.io 来 Go 的拉取依赖包
> make
> ```
> 
> 对于 node/typescript 这块，可以使用 [淘宝 NPM 镜像](https://developer.aliyun.com/mirror/NPM)。
> 例如：
> 
> ```shell
> # 使用 npm 包管理器
> npm config set registry https://registry.npm.taobao.org/
> ```
> 
> 或者:
> 
> ```shell
> # 使用 yarn 包管理器
> yarn config set registry https://registry.npm.taobao.org/
> ```

funny job！
