### ISSUE TITLE
Geo preview功能能否加入腾讯或高德地图支持？

### ISSUE THREAD

**Issue by zgl018** [RenzHoly/Mongood#76]
mongo客户端目前nosqlbooster用的最多，其中一个痛点就是nosqlbooster无法展示gui地图位置信息。
试用了一下这个软件我觉得界面还可以，很多功能可以深挖。
国内大部分做geo相关的公司mongo库里存的都是gcj02，针对这个能否出一个切换按钮，使地图渲染使用高德？
key的话可以让用户自己填自己的。
另一个痛点是无法展示轨迹信息，比如多选了多个带有geo point 的点，能否按照查询结果的顺序调用高德的轨迹渲染api在地图上展示轨迹。
解决了这两点那真的其它的客户端都可以卸载了。
（还有个小问题，新建索引的时候真的有点迷惑
`return {
  background: true
}
`
看到这个有点迷惑，没有nosqlbooster的可视化来的直观

**Comment by RenzHoly** [comment]
感谢使用！

地图渲染打算做成可以自己配置一个字符串模板，通过替换其中的经度纬度参数实现渲染，用高德的静态地图API https://lbs.amap.com/api/webservice/guide/api/staticmaps

地图轨迹，现在想不到怎么做比较优雅，感觉用户多选了geo point，不一定就是要画出地图轨迹

索引和用户功能目前做的比较粗糙，需要打磨打磨

**Comment by zgl018** [comment]
> 地图轨迹，现在想不到怎么做比较优雅，感觉用户多选了geo point，不一定就是要画出地图轨迹
其实还有更多复杂场景，比如地理围栏的展示，mongo的geojson polygon 和geojson multipolygon的可视化展示渲染起来可能更复杂

**Comment by RenzHoly** [comment]
#77 可以自定义geo point渲染了，只支持静态图片

**Comment by zgl018** [comment]
perfect
