### ISSUE TITLE
windows打开闪退，需要什么环境？

### ISSUE THREAD

**Issue by zzl221000** [RenzHoly/Mongood#90]
一台windows server 2016 能打开
还有个win10打开闪退
没有报错信息，我也没法给你反馈点啥

**Comment by RenzHoly** [comment]
安装chrome了吗

**Comment by zzl221000** [comment]
@RenzHoly chromium不行吗？必须chrome么

**Comment by RenzHoly** [comment]
看这里是支持chromium的，可能是chromium安装路径和这个pr里的不一致？
https://github.com/zserge/lorca/pull/62/files

**Comment by zzl221000** [comment]
@RenzHoly 确实不一样，能用传参的方式让用户自己填chrome路径么，或者用配置文件方式？

**Comment by RenzHoly** [comment]
好像是可以的，你试试
https://github.com/zserge/lorca/blob/master/locate.go#L18-L19

**Comment by zzl221000** [comment]
@RenzHoly 设置LORCACHROME没效果，还是装了chrome，谢谢了

**Comment by RenzHoly** [comment]
之后如果有比lorca更好的选择，会及时切换过去
https://github.com/RenzHoly/Mongood/issues/72

**Comment by zzl221000** [comment]
好用，没有其他gui那种卡顿感

**Comment by RenzHoly** [comment]
谢谢使用！专门优化过这部分。
其实如果把Page Size调整到100，看一些document比较大的数据库，还是有明显卡顿的。
也有解决办法，使用Web Workers，但有点麻烦，暂时搁置了 https://github.com/RenzHoly/Mongood/tree/web-worker

**Comment by ChungZH** [comment]
:thinking: amazing
~~怪不得折腾一早上都打不开程序呢~~
看样子这包是打不了了（
主要是 Chrome 非要在那几个指定路径，scoop 做不到 😂

**Comment by RenzHoly** [comment]
😭

**Comment by ChungZH** [comment]
其实硬要打也可以的，提示一下用户记得用 chrome 官方的安装包装一下就行哈哈哈哈哈（

**Comment by RenzHoly** [comment]
整一个呗

**Comment by ChungZH** [comment]
整好了 https://github.com/ChungZH/peach/blob/master/bucket/mongood.json

**Comment by RenzHoly** [comment]
nb
