### ISSUE TITLE
Mongo client leak at go server side

### ISSUE THREAD

**Issue by genshen** [RenzHoly/Mongood#95]
It seams there is mongo client leak at go server side.   
I added a print call (`log.Println("Hello, new connection from ", uri);`) after the client creation.  
```go
// main.go
func create(uri string) (*mongo.Client, error) {
	cached, ok := clients.Load(uri)
	if ok && cached != nil {
		return cached.(*mongo.Client), nil
	}
	client, err := mongo.NewClient(options.Client().ApplyURI(uri))
	if err != nil {
		return nil, err
	}
	err = client.Connect(ctx)
	log.Println("Hello, new connection from ", uri);       // I added a print here
	if err != nil {
		return nil, err
	}
	clients.Store(uri, client)
	return client, nil
}
```
 But it may print more than one time after I launch Mongood, e.g.
```log
2020/08/15 11:33:27 admin {"listDatabases":1}
2020/08/15 11:33:27 admin {"serverStatus":1}
2020/08/15 11:33:27 Hello, new connection from  mongodb://127.0.0.1:27017
2020/08/15 11:33:27 Hello, new connection from  mongodb://127.0.0.1:27017
2020/08/15 11:33:27 Hello, new connection from  mongodb://127.0.0.1:27017
2020/08/15 11:33:27 admin {"serverStatus":1}
2020/08/15 11:33:27 admin {"listCollections":1}
2020/08/15 11:33:27 config {"listCollections":1}
2020/08/15 11:33:27 local {"listCollections":1}
2020/08/15 11:33:27 misa {"listCollections":1}
2020/08/15 11:33:28 misa {"listCollections":1}
```
In the log above, Mongood created 3 clients. I think it should create **more clients** if the network between Mongood and Mongodb server is slower.  
Because it need some time (maybe milliseconds to seconds) to wait `mongo.NewClient` returning a client instance, then the client cache can be empty when other new `create(uri)` calls come, and these new calls will also create new client instances via `mongo.NewClient`.  

## possible fixes
1. Maybe we can add a lock(sync. Mutex) before `mongo.NewClient` to make sure there is only one create call can fall into `mongo.NewClient` calling.  
2. Don't create client instances in http Handle, setup mongo client instances once Mongood is launched.  
3. Don't fix this problem if leak is not serious.  

I'm very glad to create a PR for this if you need any help.

**Comment by RenzHoly** [comment]
I prefer the 1st solution.
Because user may create custom connection after launch. So the 2rd solution is not ok.
Please create a PR, thank you!
